name: Deploy API com Docker Compose

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Debug secrets
        run: | 
              echo "EC2_HOST = ${{ secrets.EC2_HOST }}"
              echo "EC2_SSH_KEY = ${{ secrets.EC2_SSH_KEY }}"
      - name: Deploy production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/dev/main/API-CONNECT_FONO
            git pull origin main
            docker compose down
            docker compose build
            docker compose up -d